version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres-scrum
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrum
      POSTGRES_USER: scrum
      POSTGRES_PASSWORD: 1234