version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres-scrum
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrum
      POSTGRES_USER: scrum
      POSTGRES_PASSWORD: 1234
