version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres-scrum
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrum
      POSTGRES_USER: scrum
      POSTGRES_PASSWORD: 1234
  scrum:
    build:
      context: .
    container_name: scrum
    ports:
      - "8080:8080"
    environment:
      - SCRUM_DB_HOST=postgres-scrum
    command: /bin/bash -c "sbt run"